import math

def civscorex(h,c,i,m,g,e):
    civscore = math.floor((h*3)+(c*2)+(i*4)+(m*4)+(g*5)+(e*6))
    if h == 0 and c == 0 and i == 0 and m == 0 and g == 0 and e == 0:
        return "A civilisation doomed to fall, nothing to say about it!"
    else:
        if m < 50 and g > 50:
            if e > 30 and e < 60:
                if i >= 50:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    else:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. However, social cohesion and cultural preservation are of very low priority, creating a society that places a strong emphasis on individualism and innovation over collective harmony and heritage."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a strong and effective government plays a central role, ensuring stability, good governance, and the overall welfare of its people. The economy is moderately prosperous, with a focus on sustainability and equitable distribution of resources, providing a decent standard of living for its citizens. While innovation is less emphasized, there's a deep commitment to preserving culture and fostering social harmony. This results in a society characterized by a profound sense of unity, peaceful coexistence, and a rich cultural heritage, creating a harmonious and culturally vibrant civilization."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is less emphasized, with a preference for tradition and stability, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    else:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is not a central focus, with limited emphasis on scientific research and technological progress. Social cohesion, peace, and cultural preservation are less prioritized, leading to lower levels of harmony and culture, resulting in a society that values practicality and efficiency over tradition and unity."
                    
            elif e > 60:
                if i > 50:
                    if (h + c) > 100:
                        return "In this remarkable civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is robust, striking a balance between prosperity and sustainability, offering a high standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society that sets a shining example for the world."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy strikes a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    else:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is strong, prioritizing prosperity and sustainability, providing a high standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. However, social cohesion and cultural preservation have lower priority, resulting in a society that values progress and individual achievement, leading to a dynamic but less harmonious and culturally rich environment."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is robust, striking a balance between prosperity and sustainability, offering a high standard of living. Innovation is not a primary focus, with the civilization prioritizing tradition and stability over rapid progress. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is moderate, striking a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    else:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is robust, striking a balance between prosperity and sustainability, offering a high standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are minimal, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
            else:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy, though not the strongest, strikes a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy, while struggling, strikes a balance between prosperity and sustainability, offering a decent standard of living. Innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society that thrives on its commitment to progress and tradition."
                    else:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is in a state of decline, characterized by economic challenges and underdevelopment, which impact the overall standard of living. However, innovation is paramount, fostering scientific research, technological progress, and creativity for development. Social cohesion and cultural preservation are given little importance, resulting in very low harmony and culture. This civilization places a strong emphasis on governance and progress, even at the expense of social and cultural harmony."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is struggling, marked by economic challenges and limited prosperity, which affects the standard of living. Innovation is practically non-existent, with minimal investment in scientific research and technological progress, resulting in stagnant creativity and development. Social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society."
                    elif (h + c) > 40 and (h + c) < 100:
                        return "In this civilization, a highly effective and stable government ensures good governance, accountability, and the well-being of its citizens. The economy is struggling, with significant challenges that limit prosperity, but the focus remains on sustainability and providing a decent standard of living. Innovation, unfortunately, lags behind, hampering scientific research, technological progress, and creativity for development. Despite these economic setbacks, social cohesion, peace, and cultural preservation are central, with a collective emphasis on heritage and peaceful coexistence, creating a harmonious and culturally rich society that values its traditions and social unity."
                    else:
                        return "In this civilization, a highly authoritarian and stable government enforces strict control and order, sometimes at the expense of individual freedoms. The economy is stagnant and inefficient, marked by widespread poverty and economic hardship. Innovation is stifled, with little investment in scientific research or technological progress. Social unrest and disharmony are prevalent, and cultural heritage is often neglected, resulting in a society marked by disunity and a lack of cultural richness."
        if m < 50 and g < 50:
            if e > 50:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a feeble and unreliable government struggles to maintain order and often succumbs to corruption, leaving its citizens disillusioned and powerless. The economy, while supposedly good, is better described as an uneven patchwork of wealth and poverty, with a small elite reaping the rewards while many toil in poverty. Innovation, though touted as important, often falls by the wayside due to a lack of government support and a culture of stagnation. The emphasis on social cohesion and culture is more a smokescreen for stifling dissent and preserving the status quo, all while presenting a facade of a harmonious society."
                    else:
                        return "In this civilization, a weak and unstable government struggles to provide effective governance, leading to corruption, mismanagement, and the neglect of its citizens' well-being. The economy, though showing promise, is hindered by inefficiency and lack of investment in essential sectors, resulting in an unstable and unequal standard of living. While innovation is acknowledged, it is often stifled by bureaucracy and a lack of resources, hindering scientific progress, technological advancement, and stifling creativity. Social cohesion is lacking, with divisions and conflicts prevalent, and a sense of collective responsibility for peace and unity is scarce. Cultural heritage is devalued and under threat, as the society prioritizes short-term gains over the preservation of its rich traditions, resulting in a culturally barren and fragmented society."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a feeble and unstable government struggles to maintain control and provide basic services, resulting in widespread corruption and discontent among the populace. The economy, while somewhat prosperous for a select few, is characterized by extreme inequality, leaving a significant portion of the population in poverty and hardship. Innovation is all but non-existent, stifled by political and economic elites who prioritize their own interests over progress, resulting in a stagnant and technologically backward society. On a more positive note, social cohesion and cultural preservation are central to the civilization. The people find solace in their cultural heritage, maintaining traditions and values that offer a sense of identity and belonging. While harmony is often disrupted by political turmoil and economic disparities, there is still a shared desire for peaceful coexistence. However, this harmonious and culturally rich society is overshadowed by the struggles caused by a weak government, an exploitative economy, and a lack of innovation."
                    else:
                        return "In this civilization, a weak and unstable government struggles to maintain order and provide for its citizens, resulting in corruption, mismanagement, and discontent among the population. The economy is in a constant state of turmoil, marked by inequality, poverty, and environmental degradation, offering little hope for a decent standard of living for the majority. Innovation is virtually nonexistent, with a lack of investment in research and development, hindering any prospects of progress or creativity. Social discord, conflict, and cultural erosion are pervasive, with a fractured society that places minimal importance on heritage and peaceful coexistence. Instead, this civilization is marked by divisions, mistrust, and the loss of cultural identity, resulting in a society struggling to find harmony and purpose in a bleak and disheartening environment."
            else:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a weak and ineffective government struggles to provide good governance, accountability, and the well-being of its citizens. The economy is feeble, teetering on the brink of instability, failing to offer a decent standard of living to the majority. While innovation is considered important, it remains largely stunted due to limited resources and political inefficiencies. Social cohesion and cultural preservation are central, but the collective emphasis on heritage and peaceful coexistence often masks underlying societal discontent. This results in a harmonious, yet economically challenged and politically unstable society."
                    else:
                        return "In this civilization, a weak and unstable government struggles to provide effective governance, accountability, or ensure the well-being of its citizens. The economy is feeble, teetering on the brink of collapse, failing to provide even a basic standard of living for the majority. Innovation is stunted, hindering scientific research and technological progress, leaving the society mired in stagnation. Social cohesion is severely lacking, leading to persistent unrest and conflicts, while cultural preservation is an afterthought, with heritage eroding due to neglect and indifference. This civilization is marred by discord, economic hardship, and a bleak outlook, as the government's ineffectiveness and ailing economy overshadow any potential for progress or cultural richness."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a weak and unstable government struggles to maintain order, leading to inefficiency, corruption, and the neglect of its citizens' needs. The economy is stagnant, marked by widespread poverty and a lack of opportunities, resulting in a low standard of living for most. Innovation is virtually nonexistent, stifling scientific progress and technological advancement, condemning the society to stagnation and underdevelopment. While there is a strong emphasis on harmony and culture, it is driven more by a desire for escapism from the hardships of daily life, rather than a genuine celebration of heritage. The society clings to its traditions not out of choice, but due to a lack of resources and opportunities, creating a culture that struggles to thrive in the face of adversity."
                    else:
                        return "In this civilization, a feeble and unstable government struggles to provide effective governance, leading to corruption, mismanagement, and the neglect of its citizens. The economy is weak, teetering on the brink of collapse, with high unemployment and poverty rates, resulting in a low standard of living for most. Innovation is nearly non-existent, stifled by limited resources and a lack of investment in research and development, contributing to stagnation and decline. Social cohesion is shattered, with constant internal strife and a disregard for cultural heritage, resulting in a fractured and unstable society that is devoid of harmony and cultural richness."
        if m > 50 and g < 50:
            if e > 50:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a highly militarized society operates under a weak and corrupt government, perpetuating a culture of repression and fear. The economy, while seemingly strong, is driven by military-industrial complexes, leading to vast economic inequality and exploitation. Innovation is harnessed for military dominance rather than the betterment of society, resulting in the stagnation of civilian technologies and creative suppression. Social cohesion is enforced through authoritarian measures, stifling dissent and creating a facade of harmony, while cultural preservation is used as a tool for propaganda and control, leading to a superficial and manipulated cultural heritage. This civilization, beneath the veneer of strength, is marked by oppression, inequality, and the suppression of individual and collective freedoms."
                    else:
                        return "In this civilization, a weak and unstable government breeds corruption, inefficiency, and a disregard for the well-being of its citizens. The economy is fragile, with a constant struggle between short-term gains and long-term sustainability, resulting in a barely acceptable standard of living. While innovation is theoretically encouraged, bureaucratic red tape and a lack of investment stifle scientific research, technological progress, and creativity. Social discord and internal conflicts run rampant, undermining any hope for peace, and cultural heritage is ignored or even actively eroded as the society prioritizes individual interests over collective well-being. This civilization, unfortunately, presents a bleak and unsustainable future, marked by governance failures, economic fragility, innovation stagnation, and a society torn by discord and cultural decay."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a weak and unstable government struggles to provide good governance, leading to corruption, inefficiency, and a disregard for the well-being of its citizens. The economy is underdeveloped, lacking the resources and infrastructure needed to provide a decent standard of living for most of its population. Innovation is stifled, with little emphasis on scientific research, technological progress, or creativity for development. Social cohesion is strained, with frequent internal conflicts, and the rich cultural heritage is overshadowed by the challenges of daily life. The collective emphasis on heritage and peaceful coexistence remains a distant dream in this society, as it grapples with discord, underdevelopment, and cultural erosion."
                    else:
                        return "In this civilization, a highly ineffective and unstable government struggles to provide basic governance, accountability, and the well-being of its citizens. The economy is weak, marked by economic disparities, limited opportunities, and a poor standard of living for most. Innovation is nearly non-existent, hindering scientific research, technological progress, and stifling creativity for development. Social cohesion and harmony are elusive, leading to persistent unrest and divisions within the society. The cultural heritage is eroding rapidly, with little emphasis on preservation, resulting in a society devoid of a rich cultural identity, plagued by conflicts, and marked by economic hardship."
            else:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, despite a strong military presence, a weak government grapples with inefficiency and corruption, often struggling to ensure good governance, accountability, and the well-being of its citizens. The economy, similarly weak, teeters on the edge of sustainability, failing to provide a decent standard of living for the majority.\nWhile innovation is paramount, fostering scientific research, technological progress, and creativity for development, the fruits of this progress often remain concentrated in the hands of the powerful elite, exacerbating inequality.\nThe silver lining lies in the people's resilience to these challenges. Social cohesion, peace, and cultural preservation remain central, with a collective emphasis on heritage and peaceful coexistence. Despite the lack of government support, this civilization has managed to create a harmonious and culturally rich society. However, the looming shadow of the military factor hangs heavy, as its might is often used to suppress dissent and maintain the status quo, leaving the majority of citizens in a perpetual struggle for a better life."
                    else:
                        return "In this civilization, a weak and ineffective government struggles to maintain control and provide for its citizens, resulting in widespread corruption and inequality. The economy is in a state of chronic instability, with a vast wealth gap between the elite and the impoverished, leading to a grim standard of living for most. However, innovation thrives as a means of survival, with a fierce determination to overcome adversity through scientific progress and creative solutions.\nUnfortunately, social cohesion is tenuous, and the civilization grapples with frequent conflict and unrest. Harmony is a distant dream, as the populace is divided along socioeconomic lines, leading to a fractured and strife-ridden society. Cultural preservation is a faint echo of the past, overshadowed by the constant struggle for basic needs, leaving a civilization on the brink of collapse, teetering on the precipice of its own demise."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a weak and unstable government struggles to provide effective governance, leading to corruption, inefficiency, and a lack of accountability. The economy is feeble, marked by poverty and stagnation, resulting in a low standard of living for most citizens. Innovation is virtually non-existent, stifling any potential for scientific advancement or creativity.\nYet, amidst this grim backdrop, social cohesion, peace, and cultural preservation stand as the last bastions of hope. The citizens rally together in the face of adversity, finding solace in their shared cultural heritage and values. In a world fraught with despair, they cling to the remnants of their history and traditions, seeking solace in the preservation of their unique cultural identity. This civilization, though plagued by governmental ineptitude and economic hardship, manages to maintain a tenuous sense of harmony and cultural richness as a testament to the resilience of the human spirit."
                    else:
                        return "In this civilization, a highly oppressive and corrupt government maintains a stranglehold on power, suppressing dissent and exploiting its citizens for personal gain. The economy is dismal, characterized by extreme poverty, limited opportunities, and stark income inequality. Innovation is stifled, with intellectual freedom and creativity brutally suppressed in favor of maintaining the status quo.\nSocial divisions and discord run deep, and cultural heritage has been eroded by years of strife and authoritarian rule. Instead of a harmonious and culturally rich society, this civilization is marred by the scars of its tumultuous past, where the individual is often sacrificed for the whims of the powerful few."
        if m > 50 and g > 50:
            if e > 50:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and stable government may give an illusion of good governance, but in reality, it can sometimes veer towards authoritarianism. Accountability mechanisms may be overshadowed by a concentration of power, limiting individual freedoms and stifling dissent. The strong government's control extends into many aspects of daily life.\nThe economy, while seemingly strong, often prioritizes the interests of the ruling elite. Wealth inequality persists, with a significant wealth gap between the privileged few and the majority of citizens. This civilization's focus on sustainability might be superficial, as environmental concerns may take a backseat to economic growth, leading to long-term ecological challenges.\nInnovation is indeed paramount, but it's driven by a narrow agenda dictated by the government. Scientific research and technological progress are often channeled towards military advancements and surveillance, rather than benefiting the broader population. Creativity is stifled by strict government control over education and the arts.\nWhile there is a facade of social cohesion and cultural preservation, the reality is that the emphasis on harmony can sometimes suppress dissent and diversity. A controlled narrative is imposed, and cultural preservation can be used to reinforce an authoritarian regime's power. Dissent and diverse cultural expressions are often suppressed, leading to cultural stagnation.\nIn summary, while this civilization portrays itself as a well-balanced and harmonious society, the strong elements of government control, economic inequality, and limitations on personal freedoms cast a shadow over the veneer of prosperity and cultural richness. The civilization's facade of stability and cultural preservation may come at the cost of individual liberties and true social progress."
                    else:
                        return "In this civilization, a highly authoritarian and oppressive government exerts tight control over its citizens, suppressing dissent and prioritizing its own interests over the well-being of the people. The economy is characterized by extreme inequality, with a small elite enjoying vast wealth while the majority struggle to make ends meet. Innovation is stifled, with only state-approved advancements permitted, often serving military or surveillance purposes.\nSocial cohesion is virtually non-existent, as fear and distrust permeate society due to government surveillance and a culture of informing on one another. Cultural preservation is used as a tool for control, with the government manipulating heritage to reinforce its authority. The society is marked by a lack of harmony, as citizens live in constant fear of persecution, and cultural richness is only a façade used to maintain the regime's grip on power.\nOverall, this civilization is a dystopian nightmare, where a powerful and oppressive government ensures its own interests at the expense of the people, economic disparities are extreme, innovation is tightly controlled, and social harmony and cultural preservation are manipulated for the benefit of the ruling elite, leading to a society marked by fear, distrust, and suffering."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a highly authoritarian and repressive government maintains control through strict regulations, limiting personal freedoms in the name of stability. The economy is dominated by a powerful elite, leading to significant income inequality and limited opportunities for the majority of citizens. Despite the government's emphasis on military strength, the innovation is stifled by oppressive policies and lacks the capacity for genuine progress. While the society appears harmonious on the surface, it is achieved through the suppression of dissent and conformity to rigid cultural norms, stifling individual expression and diversity."
                    else:
                        return "In this civilization, a highly authoritative and rigid government maintains control at the expense of personal freedoms, often suppressing dissent and opposition. The economy is highly skewed, with wealth concentrated among the elite, leaving many citizens struggling to attain a basic standard of living. Innovation is stifled, discouraging creativity and technological advancement due to oppressive policies and a lack of investment in research and development.\nSocial divisions are pronounced, leading to unrest, conflict, and a general sense of disillusionment among the population. Cultural preservation is mandated by the state, resulting in a stifling environment where the creative expression is stifled, and the rich tapestry of heritage is reduced to a monotonous, state-approved narrative.\nThe civilization, while appearing strong on the surface, is characterized by a stark divide between the powerful and the marginalized, limited opportunities for personal growth, and a pervasive sense of discontent. The facade of stability masks a society plagued by internal strife, inequality, and a lack of freedom."
            else:
                if i > 50:
                    if (h + c) > 100:
                        return "In this civilization, a highly authoritarian government dominates every aspect of life, using its strong military to suppress dissent and maintain control. The economy, while technically functional, is heavily skewed towards supporting the military and those in power, leaving the majority of citizens in a state of poverty and dependency. Innovation, though present, is largely channeled for military and oppressive purposes, stifling creative and scientific potential for the betterment of the populace.\nWhile there's a facade of social cohesion, it's achieved through fear and strict government surveillance, and cultural preservation is manipulated to reinforce the regime's ideology. The society, far from being harmonious, is fraught with tension and division as citizens live in constant fear, lacking freedom and basic human rights."
                    else:
                        return "In this civilization, a highly authoritarian government, while strong in terms of control and military might, prioritizes its own interests over the well-being of its citizens. The economy, while functioning, is largely geared toward sustaining the ruling regime and its military, leaving most of the population in a state of poverty and limited economic opportunities. Innovation, while technically encouraged, serves primarily the ruling elite and the military-industrial complex, leading to technological advancement in weaponry and surveillance rather than the betterment of society.\nSocial cohesion is weak, as the government promotes division and enforces conformity through fear and repression, while cultural preservation is selectively utilized as a tool for propaganda. The society lacks true cultural richness as the government's control over arts and culture stifles creativity, and dissent is ruthlessly suppressed. The overall atmosphere is one of fear, oppression, and the suppression of individual freedoms, making it a grim and oppressive society."
                else:
                    if (h + c) > 100:
                        return "In this civilization, a highly effective and authoritarian government enforces strict control and order, prioritizing its own power and interests over the well-being of its citizens. The economy is weak, struggling to provide even basic necessities to the population, leading to widespread poverty and inequality. Innovation is heavily suppressed, with a focus on maintaining the status quo and limiting intellectual freedom, stifling any potential progress or creativity.\nSocial cohesion is forced upon the population through strict surveillance and propaganda, rather than arising naturally. Cultural preservation is used as a tool for political manipulation, with the government shaping and controlling the culture to serve its own agenda. The society, while appearing harmonious on the surface, is built on fear and oppression, resulting in a lack of genuine social cohesion and a stifling environment for its citizens."
                    else:
                        return "In this civilization, a highly authoritarian government maintains strict control and suppresses dissent, leading to a lack of personal freedoms and accountability. The economy is stagnant and heavily centralized, resulting in widespread poverty and a large wealth gap. Innovation is stifled, with little investment in research or technological progress, leaving the society technologically backward.\nSocial cohesion is weak, with high levels of distrust and division among the population, leading to social unrest and conflict. Cultural preservation is disregarded, as the government actively discourages cultural expressions and heritage, eroding the society's once-rich traditions. The civilization is marked by oppressive governance, economic hardship, technological stagnation, social strife, and a loss of cultural identity, creating a disheartening and bleak environment for its citizens."
                    
            
